#!/bin/sh

# This example shows the possibility to use OpenMP parallel computing for tensile loading of a cubic sample.

THEPWD=`pwd`

#cd ../../../../src
#make omp

cd $THEPWD

rm -rf post

OMP_NUM_THREADS=8
export OMP_NUM_THREADS

../../../../src/lmp_omp -in cube_tension.in
